### ISSUE TITLE
blindfold doesn't take links into account as outlined by toptal/gitignore

### ISSUE THREAD

**Issue by iwishiwasaneagle** [Eoin-McMahon/blindfold#10]
As can be seen here 
![image](https://user-images.githubusercontent.com/12383029/112069971-bdaaa600-8b64-11eb-924a-4bf6ed6ff57c.png)
 the LaTex gitignore is wrong.

LaTex.gitignore can be seen here https://github.com/toptal/gitignore/blob/5d40f2d6ab5374bd584298de350849e57b25aa10/templates/LaTeX.gitignore#L1

with the actual content found here https://github.com/toptal/gitignore/blob/master/templates/TeX.gitignore

**Comment by Eoin-McMahon** [comment]
Thanks for pointing this out i will look into it.
p.s add `.cargo` to your path so you can run rust tools by just using their name in the future

**Comment by iwishiwasaneagle** [comment]
Quick follow up:

https://www.toptal.com/developers/gitignore/api/latex

**Comment by Eoin-McMahon** [comment]
As outlined in their github repository, you can use the argument "tex" for latex gitignores.
